MAKE_TREE_UTILS_FILES = destroyers redir_utils

MAKE_TREE_UTILS_SRCS_DIR = make_tree
MAKE_TREE_UTILS_SRCS_SUB_DIR = utils

MAKE_TREE_UTILS_SRCS = $(addprefix $(SRCS_DIR)/$(MAKE_TREE_UTILS_SRCS_DIR)/$(MAKE_TREE_UTILS_SRCS_SUB_DIR)/, $(addsuffix .c, $(MAKE_TREE_UTILS_FILES)))

MAKE_TREE_UTILS_OBJS = $(addprefix  $(OBJS_DIR)/$(MAKE_TREE_UTILS_SRCS_DIR)-$(MAKE_TREE_UTILS_SRCS_SUB_DIR)-, $(addsuffix .o, $(MAKE_TREE_UTILS_FILES)))

$(OBJS_DIR)/$(MAKE_TREE_UTILS_SRCS_DIR)-$(MAKE_TREE_UTILS_SRCS_SUB_DIR)-%.o: $(SRCS_DIR)/$(MAKE_TREE_UTILS_SRCS_DIR)/$(MAKE_TREE_UTILS_SRCS_SUB_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@ -I $(INCLUDES_DIR)